name: Clean Workflow

on:
  workflow_dispatch:

  schedule:
    - cron: '55 14 */7 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean Bucket
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Action Bot"
          rm -rf .git
          git init
          git add .
          git commit -am "Update"
          git remote add origin https://Apocalypsor:${{ secrets.REPO_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push -f -u origin master
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Apocalypsor/Workflows-Cleaner'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install
      - name: Clean
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          EXPIRE_TIME: '1h'
        run: pipenv run python run.py
